FROM python:3.10-slim

WORKDIR /dev

COPY requirements.txt requirements.txt
RUN apt-get update && apt-get install git -y
RUN pip3 install -r requirements.txt
RUN pip3 install "git+https://github.com/openai/whisper.git" 
RUN apt-get install -y ffmpeg

COPY . .

ENTRYPOINT ["python3", "transcribe.py"]
